itay-grudev/SingleApplication

README.md, singleapplication.cpp, singleapplication.h
Details:
* Improved unsafe C-style macros inheritance approach to the project-wide
DEFINES: it is unspecified in
which order source files are being preprocessed ones, so in
singleapplication.cpp the class might be inherent of default-specified
base, while in main.cpp this can be a user-provided QAPPLICATION_CLASS
definition.
* Replace Qt's pseudo-keywords to more library-independent counterparts
('emit -> Q_EMIT', etc)
* Indentation fixes (80 character column-width)
* Rearragned #include statements: from most platform-independen to more
app-specific.
* Fixed some grammar typos.
* README.md updated respectively.
=> Adaptation to Qt's pimpl idiom design. Improved inheritance safety.

singleapplication.cpp, singleapplication.h
Some applications may need to force single instance regardless of the application version or the application file path.
On Windows, the file path is case-insensitive, so the application file path need to be lowercased first before used for hashing.
According to Qt's document, QLocalServer::UserAccessOption needs to be set on the socket server, so that a non elevated process can connect to the server created by an elevated process.
=> Allow to exclude some data from hashing the server name & some Windows-related improvements

singleapplication.cpp, singleapplication.h
When username contains Unicode characters, [wcstombs()](http://www.cplusplus.com/reference/cstdlib/wcstombs/) may fail to translate it and return (size_t)-1.
`length = (size_t)-1` is a very large unsigned number and will cause `appData.addData( username, length )` to crash.
Example:
```
const wchar_t str[] = L"测试";
char buffer[512];
size_t length = wcstombs( buffer, str, 512 );
// now length is 18446744073709551615
```
=> Fix crash when username contains Unicode characters

singleapplication.cpp
When SingleApplicationPrivate instance destroys, QLocalServer object instance (_server_) will not be destroyed and the memory allocated for it will leak.
=> Fix memory leak on SingleApplicationPrivate destruction

singleapplication.cpp
When I'm trying to build singleapplication using cross-compilation (MXE (M cross environment)) a compilation error appears :
singleapplication.cpp: In member function 'void SingleApplicationPrivate::genBlockServerName(int)':
singleapplication.cpp:102:52: error: cannot convert 'wchar_t*' to 'LPSTR {aka char*}' for argument '1' to 'WINBOOL GetUserNameA(LPSTR, LPDWORD)'
if( GetUserName( username, &usernameLength ) ) { 
Mingw32 in MXE for some reason can not by itself determine the appropriate type for the function.
Using GetUserNameW instead GetUserName fixes the problem
=> Fixed compilation error: cannot convert wchar_t* to LPSTR {aka char*}

singleapplication.cpp, singleapplication_p.h
fixed instanceId reading from only one byte in deserialization of message, cleaned up serialization code using QDataStream, changed connection type to use quint8 enum rather than char
I loosely/quickly tested these changes on windows 7 using mingw 5.3 and msvc 2017.
=> removed c style casts and eliminated all clang warnings, ... 

singleapplication.pri
This should not break any windows builds as the windows filesystem is case-insensitive.
=> replace -lAdvapi32 with -ladvapi32 which broke the build on mxe

examples/basic/main.cpp, examples/calculator/main.cpp, examples/sending_arguments/main.cpp, singleapplication.cpp
I was having a bug to send a message to the primary app. The message sent by the second process was not received correctly. The issue is here: 
```c++
QByteArray msgBytes = nextConnSocket->read(nextConnSocket->bytesAvailable() - static_cast<qint64>(sizeof(quint16)));
QByteArray checksumBytes = nextConnSocket->read(sizeof(quint16));
```
When the message is sent immediately following a connection, both messages are concatenated and available to read. Therefore, the checksum is read beyond the init message and that causes an invalid connection.
The other patch is simply a case fix of the include file. On Linux, the file system is case sensitive and without the correct case, the include file is not found.
Thanks!
=> Fix sendmessage

singleapplication_p.cpp, singleapplication_p.h
The waitForReadyRead() is blocking the event loop of the main application. This patch introduces asynchronous event processing of the initialization message. Because we receive the header and the body in possibly two steps, the state is keept in a map.
This solves a crash during the checksum computation due to an empty buffer. This condition was occuring because the message header and the body may not be available at once. We should read only when the bytes are actually availables.
There is also a small fix on Windows, where the compilation was failing due to an undefined variable.
Thanks!
=> Async socket processing

singleapplication.cpp
flush() is non-blocking so it can return false when requiring blocking, see https://doc.qt.io/qt-5/qlocalsocket.html#flush
This means sendMessage() will return to the application with false even though data was actually written in waitForBytesWritten().
You should instead rely on the return value of waitForBytesWritten() since you do that anyway.
Also I don't understand the point of doing fush() before waitForBytesWritten(), so changing the order. Not sure flush is needed at all though.
=> Fix return value of sendMessage()

singleapplication_p.cpp
1. This is faster, using a command is slow and can easily timeout
2. You already use native functions for Windows
3. It compiles on Linux, macOS and openBSD (I've tested all 3)
The fallback using the variable is very unlikely to occur the way it is now, but using the home directory is a bad idea for both for UNIX systems and Windows, because the home folder can differ from the username. The current approach for unix is to timeout if whoami takes to long, so if a user starts the application twice, one of the instances can timeout and the application will be started twice if the home folder is different from the username.
Also removed QSemaphore since it's not needed.
=> Use geteuid and getpwuid to get username on Unix, fallback to environment variable

singleapplication_p.cpp
Fix `comparison between signed and unsigned integer expressions` problem.
User ID is a positive integer  in Linux/UNIX(macOS, FreeBSD, Solaris), also `geteuid()` never fails with return code.
=> Fix compilation warning/error

singleapplication.cpp
* Use [QElapsedTimer](https://doc.qt.io/qt-5/qelapsedtimer.html) instead of [QTime](https://doc.qt.io/qt-5/qtime.html) because `QTime::start()`, `QTime::elapsed()` and `QTime::restart()` [was deprecated](https://github.com/qt/qtbase/blob/a0eb51c3870d90c06966dbfbe26b114f39103b60/src/corelib/time/qdatetime.h#L227) and generates compilation warnings.
* Use [QRandomGenerator](https://doc.qt.io/qt-5/qrandomgenerator.html) instead of obsolete [qrand()](https://doc.qt.io/qt-5/qtglobal-obsolete.html#qrand) with the same range.
=> Fix obsolete code warnings

examples/basic/CMakeLists.txt, examples/calculator/CMakeLists.txt, examples/sending_arguments/CMakeLists.txt
I updated examples to the latest changes in CMake.
1. No longer need to link Qt::Widgets and Qt::Core libraries.
2. Set languages explicitly to reduce CMake configuration time.
3. Do not store `QAPPLICATION_CLASS` in cache.
=> Update CMake examples

singleapplication.cpp, singleapplication.h, singleapplication_p.cpp, singleapplication_p.h
I integrated Clang Tidy in my project and noticed that it produce some warnings. I decided to fix it instead of ignore library folder. I fixed the following:
[modernize-use-override](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html#modernize-use-override)
[modernize-use-auto](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-auto.html)
[modernize-use-using](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-using.html)
[performance-unnecessary-value-param](https://clang.llvm.org/extra/clang-tidy/checks/performance-unnecessary-value-param.html)
[modernize-use-default-member-init](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-default-member-init.html)
=> Fix Clang Tidy warnings

CMakeLists.txt, examples/basic/CMakeLists.txt, examples/calculator/CMakeLists.txt, examples/sending_arguments/CMakeLists.txt
In CMake it's common to add such alternative naming for third-party libraries (like in Qt). So I added `SingleApplication::SingleApplication` for consistency with other projects (yes, it's common to use name twice for single module libraries).
=> Add library alias for CMake

singleapplication_p.cpp
Fixes MSVC [C4996](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=vs-2019) warning (it suggests to use not portable `strncpy_s`).
Also [qstrncpy](https://doc-snapshots.qt.io/qt5-5.12/qbytearray.html#qstrncpy) guarantees that `inst->primaryUser` will be '\0'-terminated
=> Use qstrncpy

singleapplication_p.cpp
define NOMINMAX before <Windows.h> inclusion to disable min/max macros
defined in it. these macros conflict with any min/max functions and it
is common practice to disable them adding NOMINMAX define.
see https://ci.appveyor.com/project/Kolcha/digitalclock4/build/job/9ikv6q2uwnomj3s1#L305 for details
=> fixed build with Qt 5.9 MSVC2017

singleapplication_p.cpp
Calling flush() after write() makes waitForBytesWritten() always return false so the connect is never successful and message is never sent to the primary in sendMessage().
You broke this in https://github.com/itay-grudev/SingleApplication/commit/3e83f5ce13c06bf6c65fb369d152cd570d718bcb
This is a similar bug to what I've fixed previously.
In general I don't think it's a good practice to release a new version the same day you make such huge changes, it would be better to allow at least a couple of days for testing.
=> Fix return value of connectToPrimary() when connect is successful

singleapplication_p.cpp
Without guard this define from https://github.com/itay-grudev/SingleApplication/commit/3230430311c3b9d027a0ef23c3657eed3caaa696#diff-35c7c4188004bde084344a3aa8eeab6dR60 introduced compilation warning/error, and can break compilation
=> Fix build issue with MinGW GCC pedantic mode

.github/workflows/build-cmake.yml, singleapplication_p.cpp
This PR fixes warning which comes from MSVC. `instanceNumber` is unsigned, so it can't be equal to `-1`.
If you apply this change, could you please draft a new minor release? I use [FetchContent](https://github.com/crow-translate/crow-translate/blob/master/cmake/ExternalLibraries.cmake) in CMake and it would be nice to point stable release instead of specific commit.
=> Fix conversion from int to quint32

.github/workflows/build-cmake.yml, singleapplication.cpp, singleapplication.h
In this PR I used const reference to avoid extra copy of `userData`. Also I bumped GitHub actions and set Ubuntu version explicitly (currently `ubuntu-latest` is old `ubuntu-16.04`, [link](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources)) to fix CI issues.
=> Use const reference and bump GitHub actions

singleapplication_p.cpp
As described in https://github.com/itay-grudev/SingleApplication/issues/121#issuecomment-734225947 the socket can still emit a `readyRead()` after `disconnect()` is emitted. This can be seen by adding a bit of debug code to the `disconnect()` signal and also in the `readyRead()` to verify the `ConnectionInfo` is missing. This would cause a new struct to be created, and think that the connection is still at the "Header" stage, which would eat the first 8 bytes of a message being sent.
Instead of removing the `ConnectionInfo` when the socket is disconnected, wait till it is actually destroyed. These changes are far simpler than I had made originally :)
This PR closes #123.
=> Remove ConnectionInfo after socket is destroyed

singleapplication_p.cpp
- Remove incorrect usage of emit on slots.
- Convert lambda connects to 4 arg: https://github.com/KDE/clazy/blob/master/docs/checks/README-connect-3arg-lambda.md
=> Fix signal-slot issues

singleapplication_p.cpp
This simplifies the randomSleep() code and also fixes `implicit conversion from 'int' to 'float' changes value from 2147483647 to 2147483648 [clang-diagnostic-implicit-int-float-conversion]` warning for old Qt versions.
=> Simplify randomSleep() for old Qt version

CHANGELOG.md, singleapplication_p.cpp
When an application is launched as AppImage, each instance is launched
from its own FUSE-mounted filesystem, so each instance has its own
executable path.
The AppImage runtime sets the environment variable APPIMAGE to the
absolute path to the .AppImage file, so we can use the content of this
variable instead of QApplication::applicationFilePath() when set.
Closes #77, #137
=> Use AppImage path for hash when running as AppImage.

README.md
Should be HTTPS instead of SSH so people with read-only access can use it.
=> Corrected Git URL in README

singleapplication_p.cpp
`void addData(const char *data, qsizetype length);` will be  deprecated from Qt 6.4, so use `QByteArrayView` from Qt 6.3
=> fix deprecated warnings on Qt6.3+

singleapplication_p.cpp
I tried to replace the old QtSingleApplication with your code in Kate:
https://invent.kde.org/utilities/kate/-/merge_requests/698
We use a bit more strict compiler settings, like no implicit conversion to/from char to strings.
Therefore these minimal fixes where needed.
I assume it would make sense to upstream them.
Another thing that catched my attention is that there is no blocking way to wait for the primary application to terminate like QtSingleApplication had via setBlock.
Would it be ok to expose the local socket to the user to allow to implement that in the API?
=> Make it compile with Qt 6.2.x and stricter compile settings

singleapplication.cpp, singleapplication.h, singleapplication_p.cpp, singleapplication_p.h
useful if the secondary instances should wait until the primary exits
use e.g. in Kate for the kate -b xyz blocking behavior
As promised in the other pull request, here my additional api for blocking send, cleaned up a bit with an extra enum.
=> Provide API for blocking sendMessage

.github/workflows/doxygen.yml, CMakeLists.txt
Fixes the Fork URL in the `documentation pointing to Doxygen Awesome instead of our GitHub.
=> Doxygen Awesome Fork URL Fix

.github/workflows/main.yml, Windows.md, examples/windows_raise_widget/CMakeLists.txt, examples/windows_raise_widget/main.cpp, examples/windows_raise_widget/windows_raise_widget.pro
Bring widget to the front when second instance is started, this is a workaround for Windows system.
=> Windows raise widget example

.github/workflows/main.yml, CHANGELOG.md, CMakeLists.txt
Fixes an error when building with [`CMAKE_LINK_LIBRARIES_ONLY_TARGETS`](https://cmake.org/cmake/help/latest/prop_tgt/LINK_LIBRARIES_ONLY_TARGETS.html) enabled.
=> Improve Windows link library dependency

CHANGELOG.md, singleapplication.cpp
Switch to the new QNativeIpcKey based QSharedMemory constructor with Qt 6.6 and higher, the old constructor will be deprecated. This also makes the library work again with the upcoming Qt 6.6 release and higher. However, there are still issues with releasing the existing memory in cases where the application is forcefully quit or crashed.
=> Use new QNativeIpcKey based QSharedMemory constructor with Qt 6.6 and higher

CHANGELOG.md, singleapplication_p.cpp
Maximum key size on macOS is PSHMNAMLEN (31).
Fixes #178
=> SingleApplicationPrivate: Use MD5 on macOS for block server name

CMakeLists.txt
A fix for the #183 issue on Windows
=> fix Could not find advapi32_LIBRARY 

.github/workflows/main.yml
The Qt5 build in the CI is broken, because Qt5 is provided for x86_64 only, while current macos runners support arm64 only. Setting MacOS to version 13 should fix this until it falls out of GitHub Support.
References:
- https://github.com/jurplel/install-qt-action/issues/238
- https://github.com/faaxm/spix/blob/master/.github/workflows/build.yml
=> fix Qt5 build on CI for MacOS which requires x86_64

.github/workflows/main.yml, CHANGELOG.md, CMakeLists.txt, FreeStandingSingleApplication, README.md, SingleApplicationConfig.cmake.in, examples/separate_object/CMakeLists.txt, examples/separate_object/main.cpp, examples/separate_object/messagereceiver.cpp, examples/separate_object/messagereceiver.h, examples/separate_object/separate_object.pro, singleapplication_p.cpp
This is a pure extension and fully backwards compatible. (Unless I made a mistake. 😉)
I have two requirements for the library that are not currently possible:
1. I want to use it as a pre-compiled library while still being able to choose my `QXxxApplication` class at build time.
2. I need to be able to decide at runtime whether to use the single instance stuff (without starting a server and so on).
This PR allows both by making the `SingleApplication` class an object that is not derived from `QXxxApplication`. On the user side, you need to instantiate a separate `SingleApplication` object after your `QXxxApplication` object. I've added a new example `separate_object` which mirrors `sending_arguments` but uses `SingleApplication` as a separate object.
Of course, the better approach would …
=> Enable app class independent usage
