README.md
singleapplication.cpp
singleapplication.h

Added stability improvements and support for secondary instances.

Secondary Instances

---

singleapplication.cpp

I've applied the same shadowed variable fix on your refactored code.

Fixed shadow variable warning

---

singleapplication.cpp

Fix error with QCoreApplication project

bugfix - change QApplication to macro QAPPLICATION_CLASS

---

singleapplication.cpp

Thank you for this great library, I use it in https://github.com/pbek/QOwnNotes!

fixed a typo

---

.gitignore
CMakeLists.txt
README.md
examples/basic/CMakeLists.txt
examples/calculator/CMakeLists.txt
examples/calculator/calculator.cpp
examples/sending_arguments/CMakeLists.txt

Since qmake will soon become obsolete in favor of CMake, I suggest adding a rule for CMake :)

Add CMake support

---

.gitignore
SingleApplication
singleapplication.pri

> Added neccessary include, and added support for qdep - @qwertysam
Closes #93

Added support for qdep

---

.gitignore
CHANGELOG.md
README.md
examples/sending_arguments/main.cpp
singleapplication.cpp
singleapplication.h
singleapplication_p.cpp
singleapplication_p.h

Added `primaryUser()`
Closes #95

v3.1.0a Added primaryUser()

---

CHANGELOG.md
README.md
singleapplication.cpp
singleapplication.h
singleapplication_p.cpp
singleapplication_p.h

SingleApplication::currentUser and codecs

---

examples/basic/CMakeLists.txt
examples/calculator/CMakeLists.txt
examples/sending_arguments/CMakeLists.txt

Sorry, I forgot to update minimum requered version in examples :)

Update minimum requered version in examples

---

.github/workflows/build-cmake.yml

Build Test on Qt 5.15
Closes #106

Build Test on Qt 5.15

---

CMakeLists.txt

It's also a better practice to only call find_package once.
Fixes #115

Update CMake to support Qt 6

---

.github/workflows/build-cmake.yml
examples/basic/CMakeLists.txt
examples/calculator/CMakeLists.txt
examples/sending_arguments/CMakeLists.txt

I also added checks for compiler warnings :)

Add Qt6 CI builds

---

README.md
singleapplication.cpp
singleapplication.h
singleapplication_p.cpp
singleapplication_p.h

I did this because I'm contributing to an app that uses user profiles and needs to have only one instance of each profile.
By the way, I tried to follow the coding style used in SingleApplication.

Allow adding unique userdata to instances

---

singleapplication.cpp
singleapplication.h

Mark getters as const

---

examples/basic/main.cpp

Removed incorrect comment in the basic example.
Fixes #131

Removed incorrect comment in the basic example

---

singleapplication.cpp
singleapplication_p.cpp
singleapplication_p.h

Please see the commit messages for details.

Fix protocol to solve #121 and #125

---

README.md

Update README to clarify sendMessage return value

---

.github/workflows/build.yml

I noticed that CI isn't triggered on PR send from another repo. This PR fixes it.

Trigger CI on PRs

---

.github/workflows/doxygen.yml

This is the documentation generation workflow.

Bug Fix: Auto-merge conflict resaolution restored old invalid code

---

.github/workflows/doxygen.yml
CMakeLists.txt

Was discussed in https://github.com/itay-grudev/SingleApplication/pull/157#issuecomment-1148744660

Add an option to disable Doxygen

---

.gitignore
LICENSE
README.md
examples/basic/main.cpp
examples/sending_arguments/main.cpp
examples/sending_arguments/messagereceiver.cpp
examples/sending_arguments/messagereceiver.h
singleapplication.cpp
singleapplication.h
singleapplication_p.cpp
singleapplication_p.h

With the permission of my collaborators @jonaski and @Shatur I would like to amend the license terms of the library to prevent it's usage as sample data for Machine Learning purposes.
I am greatly dissatisfied with how our work is used on certain AI products and how our work is consumed and not properly attributed to its authors. Such products should have at least preserved our copyright notice, as the MIT License requires, when our software is used for any of the purposes it allows.

MIT, but No Machine Learning Allowed

---

README.md

Add an note about using CMake's FetchContent module to simplify including SingleApplication into other projects

Add an example using CMakes FetchContent module
